### ISSUE TITLE
Improved graph-tool installation instructions

### ISSUE THREAD

**Issue by count0** [dawe/schist#6]
To install graph-tool via conda the actual commands are:
```
conda create --name gt -c conda-forge graph-tool
conda activate gt
```
The command currently given in the instruction will not work.

It might be good to inform users that they can install (without compilation) using homebrew in MacOS, and also in Ubuntu/Debian. The installation instructions are here: https://git.skewed.de/count0/graph-tool/-/wikis/installation-instructions

**Comment by stuarteberg** [comment]
I recommend the following instructions.  FWIW, I tested these on my machine (a Mac) and successfully ran `conftest.py`.

---

`schist` has the following dependencies:

- `numpy`
- `scipy`
- `anndata`
- `pandas`
- `scanpy`
- `graph-tool`

[Conda][1] users can create an environment with all of them using the following commands:

[1]: https://docs.conda.io/en/latest/miniconda.html

```bash
conda create -n schist -c conda-forge -c bioconda numpy scipy anndata pandas graph-tool scanpy
conda activate schist
```

Non-conda users should obtain `graph-tool` via either `apt-get` or homebrew (see the [graph-tool installation instructions][2]), and then use `pip` for the remaining dependencies.

[2]: https://git.skewed.de/count0/graph-tool/-/wikis/installation-instructions

Since `schist` itself is not yet available on PyPI or anaconda.org, you must clone the git repo and install it from source.  Once you've installed the above dependencies, run the following commands:

```bash
git clone https://github.com/dawe/schist.git
cd schist
pip install .
```

**Comment by dawe** [comment]
Thanks for for the comments, I will update installation instructions. 
I was thinking to provide a conda recipe for `schist`, but I never did that, give me time to study.
